### ISSUE TITLE
Multi-line reaction cause access violationg exception.

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1232]
**Steps to Reproduce**
Open ketcher.
Add reaction "C1(C)C(C)=C(C)C=C(C)C=1.C1(C)C(C)=C(C)C=C(C)C=1.O.O.[OH+2]=O.O=O>>C1(C)C(C(O)=O)=C(C)C=CC=1.C1(C)C(C(O)=O)=C(C)C=CC=1"
Then add reaction "C>>C".
Try to save or layout - got error "Convert error! exception: access violation reading 0x0000000000000028"

From logs: 
Traceback (most recent call last):
  File "C:\Users\Arush\source\repos\Indigo\utils\indigo-service\backend\service\v2\indigo_api.py", line 462, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Arush\source\repos\Indigo\utils\indigo-service\backend\service\v2\indigo_api.py", line 1007, in clean
    md = load_moldata(
  File "C:\Users\Arush\source\repos\Indigo\utils\indigo-service\backend\service\v2\indigo_api.py", line 336, in load_moldata
    md.struct = indigo.loadReaction(molstr)
  File "c:\python\python38\lib\site-packages\indigo\indigo\indigo.py", line 554, in loadReaction
    self._lib().indigoLoadReactionFromString(string.encode())
OSError: exception: access violation reading 0x0000000000000028

**Comment by AliaksandrDziarkach** [comment]
Also can be reproduced by load attached file and try to save or layout it.
[issue1232.zip](https://github.com/epam/Indigo/files/12369978/issue1232.zip)
