### ISSUE TITLE
The enhanced-latest version of the container does not start

### ISSUE THREAD

**Issue by digitalroll** [epam/Indigo#1233]
When launching the `enhanced-latest` container, the following errors occur:

```
2023-08-18 13:57:37 /usr/local/lib/python3.9/site-packages/pydantic/_migration.py:276: UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.
2023-08-18 13:57:37   warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
2023-08-18 13:57:37 Traceback (most recent call last):
2023-08-18 13:57:37   File "/usr/local/bin/indigo_service", line 5, in <module>
2023-08-18 13:57:37     from indigo_service.indigo_http import run_debug
2023-08-18 13:57:37   File "/usr/local/lib/python3.9/site-packages/indigo_service/indigo_http.py", line 26, in <module>
2023-08-18 13:57:37     from indigo_service import jsonapi, service
2023-08-18 13:57:37   File "/usr/local/lib/python3.9/site-packages/indigo_service/jsonapi.py", line 50, in <module>
2023-08-18 13:57:37     class PrimitiveFormat(BaseModel):
2023-08-18 13:57:37   File "/usr/local/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
2023-08-18 13:57:37     private_attributes = inspect_namespace(
2023-08-18 13:57:37   File "/usr/local/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 291, in inspect_namespace
2023-08-18 13:57:37     raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
2023-08-18 13:57:37 TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

**Comment by T1t4m1un** [comment]
I met this problem too.

**Comment by T1t4m1un** [comment]
It seems that because a higher version of `pydantic` is installed by carrying dependencies in `setup.py`, the lower version of `pydantic` is no longer installed during `pip install`. Just add a line `"pydantic==1.10.8",` at the beginning of `install_requires` in `setup.py` and it will be fine
