### ISSUE TITLE
Update of Indigo Knime nodes

### ISSUE THREAD

**Issue by Richards999** [epam/Indigo#762]
With the new Knime 4.6 release, the Indigo chemistry nodes are no longer compatible. 
they are really useful nodes and it would be great to have them updated for everyone to use.

Thanks.

**Comment by mkviatkovskii** [comment]
Hello @Richards999,
Thank you for notifying us on this issue. I've started working on it, hope to provide you an updated version soon.

**Comment by Richards999** [comment]
Thanks so much. I look forward to the update :-)

**Comment by BJWiley233** [comment]
@Richards999 Are you using MacOS?  So this is interesting.  I was able to install Indigo2 nodes and load KNIME 4.7.1 no problem on Ubuntu 22.04 machine but ran into [this issue with Mac OS](https://forum.knime.com/t/cannot-load-indigo-plugin/59449/6) for same KNIME version.  However KNIME 4.5.0 is able to install and load Indigo nodes fine.

FYI @mkviatkovskii there is a log at my [ticket on KNIME](https://forum.knime.com/t/cannot-load-indigo-plugin/59449/6) if interested (see knime.log).  The key is probably here with MacOS libraries:
```
Caused by: org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="2.0.0.qualifier"; osgi.identity="com.epam.indigo.knime.plugin"; singleton:="true" [id=583]
	at org.eclipse.osgi.container.Module.doStart(Module.java:614)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 188 more
Caused by: java.lang.Error: Indigo cannot find native libraries for Mac OS X 10.6
	at com.epam.indigo.Indigo.getDllPath(Indigo.java:355)
	at com.epam.indigo.Indigo.<clinit>(Indigo.java:380)
	at com.epam.indigo.knime.plugin.IndigoPlugin.<clinit>(IndigoPlugin.java:39)
```

**Comment by Richards999** [comment]
HiYes you are correct it is on macOS I am having problems. Simon. Sent from my iPhoneOn 15 Feb 2023, at 09:05, BJWiley23 ***@***.***> wrote:﻿
@Richards999 Are you using MacOS?  So this is interesting.  I was able to install Indigo2 nodes and load KNIME 4.7.1 no problem on Ubuntu 22.04 machine but ran into this issue with Mac OS for same KNIME version.  However KNIME 4.5.0 is able to install and load Indigo nodes fine.
FYI @mkviatkovskii there is a log at my ticket on KNIME if interested (see knime.log).  The key is probably here with MacOS libraries:
Caused by: org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="2.0.0.qualifier"; osgi.identity="com.epam.indigo.knime.plugin"; singleton:="true" [id=583]
	at org.eclipse.osgi.container.Module.doStart(Module.java:614)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 188 more
Caused by: java.lang.Error: Indigo cannot find native libraries for Mac OS X 10.6
	at com.epam.indigo.Indigo.getDllPath(Indigo.java:355)
	at com.epam.indigo.Indigo.<clinit>(Indigo.java:380)
	at com.epam.indigo.knime.plugin.IndigoPlugin.<clinit>(IndigoPlugin.java:39)

**Comment by steffen-fissler** [comment]
Hi @mkviatkovskii and @AlexanderSavelyev,

thanks for the development of Indigo!
Whilst we are trying with @AlexanderSavelyev to make the Indigo extension work for KNIME Analytics Platform 5.1.0, we encountered this issue again on my MacOS.

I am eager to help you publish the Indigo extension for KNIME asap, but I think that a fix for MacOS beforehand would be very much appreciated.

Is there anything I could help you with?

Very best regards
Steffen

**Comment by gio-hlx** [comment]
Hi @mkviatkovskii, I'm having the same issue on MacOS both using KNIME 4.7 and KNIME 5.1.
This is a pity as Indigo nodes are very valuable for the KNIME community. Is there any prediction of when it will be addressed?
Thanks in advance for all your efforts

**Comment by AliaksandrDziarkach** [comment]
Try to build indigo-knime using `sh install-indigo.sh` from `Indigo/utils/indigo-knime` got error:

> [ERROR] Internal error: java.lang.IllegalArgumentException: Could not find specification for custom execution environment profile 'JavaSE-21' in the target platform -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: Could not find specification for custom execution environment profile 'JavaSE-21' in the target platform
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:109)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: java.lang.IllegalArgumentException: Could not find specification for custom execution environment profile 'JavaSE-21' in the target platform
    at org.eclipse.tycho.p2.target.ee.CustomEEResolutionHandler.findSpecificationUnit (CustomEEResolutionHandler.java:51)
    at org.eclipse.tycho.p2.target.ee.CustomEEResolutionHandler.readFullSpecification (CustomEEResolutionHandler.java:40)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:195)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:134)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:1)
    at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:90)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:224)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:125)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0 (TychoMavenLifecycleParticipant.java:157)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:184)
    at java.util.stream.WhileOps$1$1.accept (WhileOps.java:99)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1685)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:129)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:527)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:513)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects (TychoMavenLifecycleParticipant.java:188)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:114)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:223)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)

Set JAVA_HOME to JavaSE-17 using `JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home sh install-indigo.sh` - all builded successfuly.

Try to build using openjdk-11 - got same error.

Looks like knime plugin could be loaded only with JavaSE-17.

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since no fix over 5 versions
