### ISSUE TITLE
Java bingo-elastic substructure search cannot use QueryMolecule as target

### ISSUE THREAD

**Issue by khyurri** [epam/Indigo#800]
**Steps to Reproduce**
```
var indigoObject = indigo.loadQueryMolecule(smiles);
var target = new IndigoRecordMolecule.IndigoRecordBuilder()
        .withIndigoObject(indigoObject).build();
``` 

**Expected behavior**
We're expecting, that target will be loaded and used by SubstructureSearch

**Actual behavior**
com.epam.indigo.IndigoException: core: <query molecule> is not a molecule
    at com.epam.indigo.Indigo.checkResult(Indigo.java:103) ~[indigo-1.7.0.jar:na]
    at com.epam.indigo.IndigoObject.serialize(IndigoObject.java:1427) ~[indigo-1.7.0.jar:na]
    at com.epam.indigo.model.IndigoRecord$IndigoRecordBuilder.withIndigoObject(IndigoRecord.java:92) ~[bingo-elastic-1.7.0.jar:na]

**Indigo/Bingo version**  
```
<dependency>
    <groupId>com.epam.indigo</groupId>
    <artifactId>bingo-elastic</artifactId>
    <version>1.7.0</version>
</dependency>

**Additional context**
Add any other context about the problem here.

**Comment by MysterionRise** [comment]
It definitely could be used in substructure search, though it’s reproduced. I’m wondering if it has something to do with the way you create molecule
@mkviatkovskii do you have an idea?

**Comment by jank9201** [comment]
@MysterionRise Hi，MysterionRise，I have test elastic substructure search with the [example](https://github.com/epam/Indigo/issues/2544) from https://lifescience.opensource.epam.com/bingo/user-manual-oracle.html#substructure-search；but it does not worked！is currently the substructure supported？or is my code wrong?
